from __future__ import annotations

from collections.abc import Iterable
from typing import Protocol

from ..models import ArtifactKey, DocumentKey, RepositoryId, SourceDocument


class StorageError(ValueError):
    """Stable persistence-contract failure."""


class ArtifactStore(Protocol):
    def initialize(self) -> None: ...
    def contains(self, key: ArtifactKey) -> bool: ...
    def put_document(self, document: SourceDocument) -> None: ...
    def put_documents(self, documents: Iterable[SourceDocument]) -> None: ...
    def get_document(self, key: DocumentKey) -> SourceDocument: ...
    def list_document_keys(self) -> list[DocumentKey]: ...
    def delete_document(self, key: DocumentKey) -> None: ...
    def validate(self) -> None: ...
    def list_artifact_keys(self, *, repository_id: RepositoryId | None = None, artifact_type: str | None = None) -> list[ArtifactKey]: ...


def document_key(document: SourceDocument) -> DocumentKey:
    return DocumentKey(repository_id=document.provenance.origin.repository_id, document_id=document.provenance.origin.document_id)


__all__ = ["ArtifactStore", "StorageError", "document_key"]
